logging:
  level:
    com.lulobank.events: DEBUG

cloud:
  aws:
    sqs:
      listeners:
        -
          name: listener1
          queueURL: http://localhost:4566/000000000000/cduarte-queue
          region: us-east-1
          maxNumberOfMessages: 10 #optional
          waitTimeSeconds: 20 #optional
          #TODO: Review if delay time is better to handle retries
          visibilityTimeout: 5 #required
          #maximumNumberOfThreads: 100 #optional
          #concurrency: 10 #optional
          #maximumQueueCapacity: 10000 #optional
        -
          name: listener2
          queueURL: https://sqs.us-east-1.amazonaws.com/900852371335/cduarte-queue
          region: us-east-1
          maxNumberOfMessages: 5 #optional
          waitTimeSeconds: 20 #optional
          visibilityTimeout: 5 #required
          maximumNumberOfThreads: 100 #optional
          concurrency: 10 #optional
          maximumQueueCapacity: 10000 #optional
      endpoint: http://localhost:4566